/* soapBarcodePrintServiceSoap11BindingProxy.cpp
   Generated by gSOAP 2.8.22 from BarcodePrintService.h

Copyright(C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "soapBarcodePrintServiceSoap11BindingProxy.h"

BarcodePrintServiceSoap11BindingProxy::BarcodePrintServiceSoap11BindingProxy()
{	this->soap = soap_new();
	this->soap_own = true;
	BarcodePrintServiceSoap11BindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

BarcodePrintServiceSoap11BindingProxy::BarcodePrintServiceSoap11BindingProxy(struct soap *_soap)
{	this->soap = _soap;
	this->soap_own = false;
	BarcodePrintServiceSoap11BindingProxy_init(_soap->imode, _soap->omode);
}

BarcodePrintServiceSoap11BindingProxy::BarcodePrintServiceSoap11BindingProxy(const char *url)
{	this->soap = soap_new();
	this->soap_own = true;
	BarcodePrintServiceSoap11BindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = url;
}

BarcodePrintServiceSoap11BindingProxy::BarcodePrintServiceSoap11BindingProxy(soap_mode iomode)
{	this->soap = soap_new();
	this->soap_own = true;
	BarcodePrintServiceSoap11BindingProxy_init(iomode, iomode);
}

BarcodePrintServiceSoap11BindingProxy::BarcodePrintServiceSoap11BindingProxy(const char *url, soap_mode iomode)
{	this->soap = soap_new();
	this->soap_own = true;
	BarcodePrintServiceSoap11BindingProxy_init(iomode, iomode);
	soap_endpoint = url;
}

BarcodePrintServiceSoap11BindingProxy::BarcodePrintServiceSoap11BindingProxy(soap_mode imode, soap_mode omode)
{	this->soap = soap_new();
	this->soap_own = true;
	BarcodePrintServiceSoap11BindingProxy_init(imode, omode);
}

BarcodePrintServiceSoap11BindingProxy::~BarcodePrintServiceSoap11BindingProxy()
{	if (this->soap_own)
		soap_free(this->soap);
}

void BarcodePrintServiceSoap11BindingProxy::BarcodePrintServiceSoap11BindingProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this->soap, imode);
	soap_omode(this->soap, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
	{"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns1", "http://ws.apache.org/axis2", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this->soap, namespaces);
}

void BarcodePrintServiceSoap11BindingProxy::destroy()
{	soap_destroy(this->soap);
	soap_end(this->soap);
}

void BarcodePrintServiceSoap11BindingProxy::reset()
{	destroy();
	soap_done(this->soap);
	soap_initialize(this->soap);
	BarcodePrintServiceSoap11BindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void BarcodePrintServiceSoap11BindingProxy::soap_noheader()
{	this->soap->header = NULL;
}

const SOAP_ENV__Header *BarcodePrintServiceSoap11BindingProxy::soap_header()
{	return this->soap->header;
}

const SOAP_ENV__Fault *BarcodePrintServiceSoap11BindingProxy::soap_fault()
{	return this->soap->fault;
}

const char *BarcodePrintServiceSoap11BindingProxy::soap_fault_string()
{	return *soap_faultstring(this->soap);
}

const char *BarcodePrintServiceSoap11BindingProxy::soap_fault_detail()
{	return *soap_faultdetail(this->soap);
}

int BarcodePrintServiceSoap11BindingProxy::soap_close_socket()
{	return soap_closesock(this->soap);
}

int BarcodePrintServiceSoap11BindingProxy::soap_force_close_socket()
{	return soap_force_closesock(this->soap);
}

void BarcodePrintServiceSoap11BindingProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this->soap, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void BarcodePrintServiceSoap11BindingProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this->soap, os);
}
#endif

char *BarcodePrintServiceSoap11BindingProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this->soap, buf, len);
}
#endif

int BarcodePrintServiceSoap11BindingProxy::FinishPrintInfo(const char *endpoint, const char *soap_action, _ns1__FinishPrintInfo *ns1__FinishPrintInfo, _ns1__FinishPrintInfoResponse &ns1__FinishPrintInfoResponse)
{	struct soap *soap = this->soap;
	struct __ns1__FinishPrintInfo soap_tmp___ns1__FinishPrintInfo;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.64.212.241:8080/axis2/services/BarcodePrintService.BarcodePrintServiceHttpSoap11Endpoint/ http://10.64.212.241:8080/axis2/services/BarcodePrintService.BarcodePrintServiceHttpSoap12Endpoint/";
	if (soap_action == NULL)
		soap_action = "urn:FinishPrintInfo";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__FinishPrintInfo.ns1__FinishPrintInfo = ns1__FinishPrintInfo;
	soap_serializeheader(soap);
	soap_serialize___ns1__FinishPrintInfo(soap, &soap_tmp___ns1__FinishPrintInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__FinishPrintInfo(soap, &soap_tmp___ns1__FinishPrintInfo, "-ns1:FinishPrintInfo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__FinishPrintInfo(soap, &soap_tmp___ns1__FinishPrintInfo, "-ns1:FinishPrintInfo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__FinishPrintInfoResponse)
		return soap_closesock(soap);
	ns1__FinishPrintInfoResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__FinishPrintInfoResponse.soap_get(soap, "ns1:FinishPrintInfoResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int BarcodePrintServiceSoap11BindingProxy::GetTime(const char *endpoint, const char *soap_action, _ns1__GetTime *ns1__GetTime, _ns1__GetTimeResponse &ns1__GetTimeResponse)
{	struct soap *soap = this->soap;
	struct __ns1__GetTime soap_tmp___ns1__GetTime;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.64.212.241:8080/axis2/services/BarcodePrintService.BarcodePrintServiceHttpSoap11Endpoint/ http://10.64.212.241:8080/axis2/services/BarcodePrintService.BarcodePrintServiceHttpSoap12Endpoint/";
	if (soap_action == NULL)
		soap_action = "urn:GetTime";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetTime.ns1__GetTime = ns1__GetTime;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetTime(soap, &soap_tmp___ns1__GetTime);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetTime(soap, &soap_tmp___ns1__GetTime, "-ns1:GetTime", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetTime(soap, &soap_tmp___ns1__GetTime, "-ns1:GetTime", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__GetTimeResponse)
		return soap_closesock(soap);
	ns1__GetTimeResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetTimeResponse.soap_get(soap, "ns1:GetTimeResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int BarcodePrintServiceSoap11BindingProxy::FinishPrintInfo_(const char *endpoint, const char *soap_action, _ns1__FinishPrintInfo *ns1__FinishPrintInfo, _ns1__FinishPrintInfoResponse &ns1__FinishPrintInfoResponse)
{	struct soap *soap = this->soap;
	struct __ns1__FinishPrintInfo_ soap_tmp___ns1__FinishPrintInfo_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.64.212.241:8080/axis2/services/BarcodePrintService.BarcodePrintServiceHttpSoap11Endpoint/ http://10.64.212.241:8080/axis2/services/BarcodePrintService.BarcodePrintServiceHttpSoap12Endpoint/";
	if (soap_action == NULL)
		soap_action = "urn:FinishPrintInfo";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__FinishPrintInfo_.ns1__FinishPrintInfo = ns1__FinishPrintInfo;
	soap_serializeheader(soap);
	soap_serialize___ns1__FinishPrintInfo_(soap, &soap_tmp___ns1__FinishPrintInfo_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__FinishPrintInfo_(soap, &soap_tmp___ns1__FinishPrintInfo_, "-ns1:FinishPrintInfo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__FinishPrintInfo_(soap, &soap_tmp___ns1__FinishPrintInfo_, "-ns1:FinishPrintInfo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__FinishPrintInfoResponse)
		return soap_closesock(soap);
	ns1__FinishPrintInfoResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__FinishPrintInfoResponse.soap_get(soap, "ns1:FinishPrintInfoResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int BarcodePrintServiceSoap11BindingProxy::GetTime_(const char *endpoint, const char *soap_action, _ns1__GetTime *ns1__GetTime, _ns1__GetTimeResponse &ns1__GetTimeResponse)
{	struct soap *soap = this->soap;
	struct __ns1__GetTime_ soap_tmp___ns1__GetTime_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.64.212.241:8080/axis2/services/BarcodePrintService.BarcodePrintServiceHttpSoap11Endpoint/ http://10.64.212.241:8080/axis2/services/BarcodePrintService.BarcodePrintServiceHttpSoap12Endpoint/";
	if (soap_action == NULL)
		soap_action = "urn:GetTime";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetTime_.ns1__GetTime = ns1__GetTime;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetTime_(soap, &soap_tmp___ns1__GetTime_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetTime_(soap, &soap_tmp___ns1__GetTime_, "-ns1:GetTime", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetTime_(soap, &soap_tmp___ns1__GetTime_, "-ns1:GetTime", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__GetTimeResponse)
		return soap_closesock(soap);
	ns1__GetTimeResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetTimeResponse.soap_get(soap, "ns1:GetTimeResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
